### ISSUE TITLE
Rake Core 빌드 에러.

### ISSUE THREAD

**Issue by devarchi33** [skpdi/rakeapi-java#1]
안녕하세요 :)

http://readme.skplanet.com/?p=13042 를 보고
Rake API 를 이용하여 Kafka 로그 프로듀서 에이전트를 만들어 보려고 합니다.

프로젝트 포크 후에  메이븐 빌드 중에
Rake API  는 빌드 성공하고,
Rake Core 빌드시에  실패 한 상타입니다. 

Rake Core 모듈의 의존성 파일을 http://mvn.skplanet.com/content/groups/public 레포지토리 에서 찾는중에 타임아웃이 나면서 빌드에러가 납니다.

http://mvn.skplanet.com/content/groups/public 으로의 접근이 막혀 있는것 같은데... rakeapi-java 라이브러리는 내부적으로만 사용하시는 건가요?

**Comment by 1ambda** [comment]
@devarchi33 안녕하세요. mvn.skplanet.com 은 SK planet 사내 메이븐 레포지토리로 외부에서는 막혀있습니다. 

필요한 모듈을 다른것으로 대체 가능한지는 @KangByeongSu 님이 답변해주실 수 있을것 같습니다. 

답변 부탁드려요 @KangByeongSu 님.

**Comment by KangByeongSu** [comment]
@devarchi33 님 안녕하세요.  위에서 말씀해 주신대로 mvn.skplanet.com은 외부에서 접근이 불가합니다. 해당 API를 내부용으로만 열어 둔 이유는, 소스 내의 default 설정 값들이 사내 환경에 특화되어있기 때문입니다. 

사내 maven repository를 사용하지 않고 사용을 원하신다면 소스를 다운 받은 후 mvn package 수행하면 RakeAPI-path/core/target path에 rake-core-VERSION.jar가 생성되어 있을 것입니다. 해당 jar를 import하셔서 사용하시면 될 것 같습니다.

https://github.com/skpdi/rakeapi-java 에 소스가 올라가있고, ReadMe에 사용방법이 명시되어 있습니다.
```
Properties properties = new java.util.Properties();
properties.setProperty("api.type", "live"); // 필수 설정 값입니다. proto, dev, live 중 한 가지를 입력해야 합니다.
properties.setProperty("service.id", "rakeapi-live01"); // 필수 설정 값 입니다. service중인 서버 이름을 넣어야 합니다.
LoggerAPI loggerAPI = LoggerAPI.getInstance(properties);
loggerAPI.log("topic", "log");
```
위와 같이 처음 LoggerAPI Singleton 객체를 생성 후 .log() 메서드를 호출하여 로그를 전송하게 되는데,

이때 사내가 아닌 사외에서 사용하시는 경우, 객체 생성시
properties.setProperty("async.kafka.bootstrap.servers","ip:port,ip:port....."); 를 추가해주셔야 합니다.

전송하시려는 카프카 브로커의 hostname또는 ip와 port를 셋팅값에 넣어주시고 호출하시면 전송이 가능할 것입니다.

**Comment by devarchi33** [comment]
repository 를 https://raw.github.com/bulldog2011/bulldog-repo/master/repo/releases/ 으로 변경하고

LoggerAPI 에서 startMonitoring(), getShuttleMessage() 을 주석처리 하고 빌드 성공했습니다. ㅎㅎ

2 메소드를 주석처리한 이유는 core 모듈에서 rakeapi-heartbeat, crypto-dic 를 의존성을 갖고 있어서 빌드가 실패 하더라구요 ㅠㅠ

일단, 빌드는 성공했으니  알려주신 방법 참고해서 만들어 보겠습니다.

@1ambda , @KangByeongSu 님 답변 감사드립니다 :)

**Comment by devarchi33** [comment]
빌드한 라이브러리 잘 동작합니다 :) 👍 

소스에 대한 분석은 더 해야할것 같습니다.ㅎㅎ;;
